spring:
  application:
    name: mobidoc-server
  
  datasource:
    url: jdbc:postgresql://localhost:5432/mobidoc
    username: mobidoc
    password: mobidoc
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api