spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mobidoc
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/mobidoc
          jwk-set-uri: http://localhost:8180/realms/mobidoc/protocol/openid-connect/certs
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api/v1

keycloak:
  realm: mobidoc
  auth-server-url: http://localhost:8180
  ssl-required: external
  resource: mobidoc-server
  bearer-only: true
  use-resource-role-mappings: true
  principal-attribute: preferred_username

logging:
  level:
    ci.mobidoc: DEBUG
    org.springframework.security: INFO